### ISSUE TITLE
Criar as primeiras paginas da wiki onde vai conter os modelos e informações sobre as regras do projeto

### ISSUE THREAD

**Issue by ViniciusAcordiSoethe** [ViniciusAcordiSoethe/portalSepe_Back#5]
Deve usar a aba de WIKI no repositório para criar as documentações do projeto

**Comment by gbaierski** [comment]
Foi desenvolvida a seguinte página contendo a explicação das ações que devem ser feitas em cada coluna do board:
https://github.com/ViniciusAcordiSoethe/portalSepe_Back/wiki/Colunas-do-fluxo-de-desenvolvimento
O intuito é auxiliar os colaboradores que ainda não estão habituados com o fluxo.
@ViniciusAcordiSoethe

**Comment by ViniciusAcordiSoethe** [comment]
Obrigado @gbaierski  achei lindo não é necessário passar por Review e nem pelo QA por ser uma demanda interna, então vou fechar essa issue com esse comment
